### ISSUE TITLE
🪶  [Feature Request] - Surface Avocano versions & avocart feature toggle 

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/avocano#147]
## Need

Investigating whether a deployed version of the client is running the correct version of Avocano with the correct use of "cart" mode. The current example from the blueprint does not. There is no way I'm familiar to quickly triangulate where in the system something might be wrong.

## Proposal

Add some metadata and info logging to the application.

* [x] **client**: Add a console.log such as "You are viewing Avocano via client v1.4.1 (purchase_mode=cart)". If cart mode isn't active, use "You are viewing Avocano via client v1.4.1 (purchase_mode=direct)"
* [x] **client container**: Add [OCI annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) to the client container, for this purpose the following three seem most likely useful:
  * org.opencontainers.artifact.created
  * org.opencontainers.image.version
  * org.opencontainers.artifact.description
* [ ] **server**

**Comment by glasnt** [comment]
A lot of this has been implemented, and since the server side doesn't have any feature toggle, and #171  is closed, I think this can also be resolved.
