### ISSUE TITLE
🐞 [Bug Report] - JavaScript errors in Chrome console

### ISSUE THREAD

**Issue by kweinmeister** [GoogleCloudPlatform/avocano#159]
**To Reproduce**
* Show JavaScript Console (View > Developer > JavaScript console)
* Launch webapp and navigate around
* Observe errors such as:  "webfont.js:28 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')"

**Expected behavior**
No errors in JavaScript console

**Comment by glasnt** [comment]
Presuming this comes from https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js via https://github.com/typekit/webfontloader. This package hasn't been updated since 2017

I'm unable to reliably reproduce this particular bug. 

This package is used in the customisation options for the application. We could investigate a different method

**Comment by glasnt** [comment]
I was able to reliably reproduce this, by causing a full refresh of the page: 

* Open a deployed version
* Click the "Avocano" heading. 


`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split') webfont.js:28`

```
 var wa = "//fonts.googleapis.com/css";
    function xa(a, b) {
        for (var c = b.length, d = 0; d < c; d++) {
            var e = b[d].split(":");
            3 == e.length && a.f.push(e.pop());
            var f = "";
            2 == e.length && "" != e[1] && (f = ":");
            a.a.push(e.join(f))
        }
    }
```

**Comment by glasnt** [comment]
There can be instances where the `window.WebFont.load` function can be called by avocano-shell.js before the config object exists (cannot reproduce locally, can reproduce on a deployed version). Adding an addition check at https://github.com/GoogleCloudPlatform/avocano/blob/main/client/src/avocano-shell.js#L94 to only load if `config.base_font` isn't empty should prevent this error. No change to webfont.js required
