### ISSUE TITLE
🛒   [Chore] - Add test coverage for add to cart button 

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/avocano#194]
## Current

Current test suite tracks the frontend changes associated with adding a checkout page.

## Requested

Add test coverage that the "Buy" label on products is changed to "Add to Cart"

**Comment by glasnt** [comment]
https://github.com/GoogleCloudPlatform/avocano/blob/main/provisioning/test/client_test.py#L89

With the changes in #155, there can be improvements for this test, in general.
