### ISSUE TITLE
🛒   [Chore] - Add test coverage for checkout API

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/avocano#195]
## Current

No API test coverage for Checkout. (Other API tests appear to be at https://github.com/GoogleCloudPlatform/avocano/blob/main/provisioning/test/server_test.py#L43)

## Requested

The Checkout API has several specific cases we would like to confirm in order to ensure content workflows around troubleshooting & investigation remain solid.

* [ ] 200 on collect request of products within inventory
* [ ] 400 on collect request on products that exceed inventory
* [ ] 501 on credit requests

**Comment by glasnt** [comment]
The lack of this meant there was a missed regression in #290 

Currently cart checkouts are failing, and our tests didn't catch this. 

I also didn't realise that the nightly errors weren't "timing out", they were waiting for a success dialog that never appeared. 

Will need to pick this up

**Comment by glasnt** [comment]
incorrect url, trying to post to checkout/, not checkout. 404 error not being passed back to dialog. 

After correcting that, `CSRF token from the 'X-Csrftoken' HTTP header has incorrect length`

Breakpoint at `django/middleware/csrf.py:_check_token_format`, the token is `'[object Promise]'`. csrfToken being passed isn't returning the final fetched value, only the promise.
