### ISSUE TITLE
🧹 [Chore] - review-warning github workflow errors on forks

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/avocano#224]
**Describe the bug**

The review-warning GitHub Workflow doesn't have access to comment on PRs where the branch is from a fork. This is a limitation of the GitHub permissions model without having an access token.

This first came up in https://github.com/GoogleCloudPlatform/avocano/pull/219.

I commented there:

> `review-warning` is failing because the permission to comment isn't extended to forks on the current permissions model, something I didn't test when I confirmed it would work. We can rip it out, skip forks, or disable the workflow until the path forward on a GitHub Actions write identity comes together (@averikitsch working on this)

> **Syntax to Skip Forks in a Step**: `if: ${{ github.event.pull_request.head.repo.fork }}`

**Expected behavior**

The review-warning never errors, it only decides whether or not to comment.

**Priority**

This check is not required for merge, but the failure is distracting.

**Comment by glasnt** [comment]
Out of scope.
