### ISSUE TITLE
🐞 [Bug Report] - Refreshing a valid URL through the browser results in a 404

### ISSUE THREAD

**Issue by bourgeoisor** [GoogleCloudPlatform/avocano#236]
**Describe the bug**
When refreshing Avocano on a page that is not root (for example, `/products`), the page shows a 404 asking to manually click a link to get back to the site.

**To Reproduce**
1. Visit the `/products` page
2. Refresh the page through the web browser (cmd+r)

**Expected behavior**
I expected the web app to load the expected page (in this case, the products page)

**Screenshots**
<img width="1084" alt="image" src="https://github.com/GoogleCloudPlatform/avocano/assets/3271352/7e447ba2-8d0c-4bad-917a-74adc38eaac3">

**Additional context**
N/A

**Comment by glasnt** [comment]
Background: This page was created in #40 to address #39, where the 404 experience was worse. 

I see this page should auto-refresh in 7 seconds, currently. 

There's possibly a better solution where this fallback isn't needed.

ping @pattishin for visibility.
