### ISSUE TITLE
🐞 [Bug Report] - Purchasing inactive products causes redirect

### ISSUE THREAD

**Issue by glasnt** [GoogleCloudPlatform/avocano#25]
**Describe the bug**

If I navigate to /products, select a not-active product (something not on the front page), and click "Buy", I'm redirected to the home page and the active product. 

Checking back on the product listing, the purchase went through. 

**To Reproduce**

1. go to https://avocano.dev/
2. click "products" 
3. select "Star Unicorn"
4. click "Buy"

**Expected behavior**

The "Oh no" popup appears
The inventory count for Star Unicorn is updated to N-1

**Actual Behaviour**

The site redirects to the active Sparkly Avocano. 
Checking the product listing, the inventory count was updated.
Transaction data matches purchased product.

**Screenshots**

[Avocano bug redirecting purchase.webm](https://user-images.githubusercontent.com/813732/216449360-73173263-e708-496e-bd88-a12731279a67.webm)

**Comment by pattishin** [comment]
PR opened!  https://github.com/GoogleCloudPlatform/avocano/pull/37

**Comment by pattishin** [comment]
PR merged, closing issue.
