### ISSUE TITLE
🐞 [Bug Report] - Annotations lost in v2

### ISSUE THREAD

**Issue by glasnt** [GoogleCloudPlatform/avocano#257]
https://github.com/GoogleCloudPlatform/avocano/pull/240 removes annotations, but there may be some we want to restore. 

Commentary from thread:

https://github.com/GoogleCloudPlatform/avocano/pull/240#discussion_r1201154814

https://github.com/GoogleCloudPlatform/avocano/pull/240#issuecomment-1558047825

**Comment by iennae** [comment]
Thanks for opening this up for a discussion. It looks like client is the new client-name in v2. not clear because no examples. 

And I THINK scaling is the other one 

 scaling {
      max_instance_count = 2
    }
    
    from documentation.

**Comment by glasnt** [comment]
For reference, the original maxScale was copied from [unicodex](https://github.com/GoogleCloudPlatform/django-demo-app-unicodex/blame/latest/terraform/service.tf#L19), through a series of copy/paste it wasn't ever adjusted because it (until now) Just Worked. Having maxScale = 100 isn't _required_, but I think we need to make sure there's docs examples on how to do this, even if we don't

**Comment by glasnt** [comment]
following up on this, yes, scaling is no longer annotation, it's now a template level attribute

```
scaling {
      min_instance_count = 1
      max_instance_count = 10
    }
```

Also, some other moving/renames

```hcl
resource "google_cloud_run_v2_service" "default" {
  
  client = "terraform" # was run.googleapis.com/client-name
  template {
      containers {
        # ...
        cpu_idle = false # was run.googleapis.com/cpu-throttling
        }
      }
      timeout = "300s"  # was timeout_seconds
      max_instance_request_concurrency = 80 # was container_concurrency
  }
}
```

The changes to annotations are listed in https://cloud.google.com/run/docs/reference/rpc/google.cloud.run.v2#service. Specifically:

> Cloud Run API v2 does not support annotations with run.googleapis.com, cloud.googleapis.com, serving.knative.dev, or autoscaling.knative.dev namespaces, and they will be rejected in new resources. All system annotations in v1 now have a corresponding field in v2 Service.
