### ISSUE TITLE
🐞 [Bug Report] - Hard coded project name in automation

### ISSUE THREAD

**Issue by chgans** [GoogleCloudPlatform/avocano#296]
**Describe the bug**
The service account for provisioning automation is hard coded here:
https://github.com/GoogleCloudPlatform/avocano/blob/main/provisioning/automation/cloudbuild.yaml#L59

AFAIU, it should instead be 
```yaml
serviceAccount: projects/${PROJECT_ID}/serviceAccounts/ci-serviceaccount@${PROJECT_ID}.iam.gserviceaccount.com
```

**To Reproduce**
Follow the https://github.com/GoogleCloudPlatform/avocano/blob/main/provisioning/automation/README.md
`gcloud builds submit --config provisioning/automation/cloudbuild.yaml` will fail with:
```
ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: could not generate access token of 'build.service_account': generic::permission_denied: IAM permission denied for service account ci-serviceaccount@avocano-admin.iam.gserviceaccount.com
```

`ci-serviceaccount` is created in `admin-project-setup.sh`, the email is created by GCP and contains `PROJECT_ID`

**Comment by glasnt** [comment]
Hi @chgans 

If memory serves, when this functionality was first added to Cloud Build, you couldn't use dynamic values in that part of the serviceAccount value. 

I'd have to confirm this would work before applying the provided patch

Also of note: this automation creates new projects; which is only possible if you have permission to do so, and you are in an organisation. This functionality (probably, last I checked) won't work in an "individual" GCP account. This is part of our testing suite where we create new projects, deploy the app, run tests, then destroy the project, to test all the scripts involved in a "clean room" environment. 


Docs and references 
https://github.com/GoogleCloudPlatform/avocano/blob/main/provisioning/automation/README.md
https://cloud.google.com/build/docs/securing-builds/configure-user-specified-service-accounts
https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
https://cloud.google.com/resource-manager/docs/creating-managing-projects#creating_a_project_using_a_service_account

**Comment by chgans** [comment]
Hi,

I do have an organisation account, with project limit lifted.
I don't understand why `admin-project-setup.sh` creates `ci-serviceaccount` in a project but  the automation code requires another `ci-serviceaccount`.
There is no reference to `ci-serviceaccount@avocano-admin.iam.gserviceaccount.com` in the docs.
This is confusing.
Do i need to create a dedicated 'avocano-admin' project and create a service account from there? Is this a "global" service account?

occurences of `ci-serviceaccount`: https://github.com/search?q=repo%3AGoogleCloudPlatform%2Favocano%20ci-serviceaccount&type=code


When i apply the proposed fix, then project-setup.sh fails on
```sh
SA_EMAIL=$(gcloud iam service-accounts list --project ${PARENT_PROJECT} --filter $SA_NAME --format 'value(email)')
```
Due to lack of permission. As i couldn't figure out how to fix this, i've hard coded this
```sh
SA_EMAIL=ci-serviceaccount@myproject-1.iam.gserviceaccount.com
```
And now i get more permission issues:
```
ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: invalid bucket "myproject-1-buildlogs"; builder service account does not have access to the bucket
```

So looks like i'm going nowhere. Maybe something is missing in the documentation.

**Comment by glasnt** [comment]
There's two issues here, that I've got solutions for in #372 

The service account email section of the `serviceAccount` value has changed since I last visited this code, and now it appears you are not blocked in using a substitution variable in this part of the variable. 

The issue you experienced around the bucket would require running the admin-project-setup.sh script. If you configure a user provided service account, you need to provide a separate logging bucket, or disable logging to Cloud Storage and have logs only going to Cloud Logging. https://cloud.google.com/build/docs/securing-builds/configure-user-specified-service-accounts#setting_up_build_logs  You can set `logging: CLOUD_LOGGING_ONLY` to avoid this.
