### ISSUE TITLE
🐞 [Bug Report] - Product Item not loading on hard refresh

### ISSUE THREAD

**Issue by pattishin** [GoogleCloudPlatform/avocano#39]
**Describe the bug**
On the client side, when attempting a hard refresh on a product item `/product/3`, the page reveals a "Not found" error.

**To Reproduce**
1. Go to local version or deployed version of avocano and route to a product item page that's not on root. (i.e `/product/3`)
2. Click on refresh button on browser.

**Expected behavior**
The product item page should refresh as usual with its content.

**Screenshots**
<img width="848" alt="Screenshot 2023-02-08 at 1 29 39 PM" src="https://user-images.githubusercontent.com/1331216/217655259-b4b49be9-f1c8-4f69-8786-a07d98ad3211.png">
<img width="953" alt="Screenshot 2023-02-08 at 1 29 29 PM" src="https://user-images.githubusercontent.com/1331216/217655346-a6572c54-05c2-4cd7-8fe8-5f0aff79f4c2.png">

**Additional context**
N/A

**Comment by pattishin** [comment]
PR opened! https://github.com/GoogleCloudPlatform/avocano/pull/40

**Comment by glasnt** [comment]
Appears resolved in #40!
