### ISSUE TITLE
🐞 [Bug Report] - Repository "containers" not found

### ISSUE THREAD

**Issue by andreif** [GoogleCloudPlatform/avocano#412]
**Describe the bug**
I am trying to follow the guide how to modify and deploy changes to the dynamic web app. 

On step 10 (Build a server container image, 2), I am executing command

```sh
cd ~/avocano/
gcloud builds submit --config \
    provisioning/server.cloudbuild.yaml
```

And after multiple steps it's trying to push the image that has been built and then fails

```
PUSH
Pushing europe-west1-docker.pkg.dev/***-***-***/containers/server
The push refers to repository [europe-west1-docker.pkg.dev/***-***-***/containers/server]
...
name unknown: Repository "containers" not found
```

I have changed `us-docker.pkg.dev` to `europe-west1-docker.pkg.dev` since it's where I am deploying to but it did not help to resolve the issue. Any ideas what went wrong?

**Comment by glasnt** [comment]
Thanks for reporting this issue, @andreif. 

As part of this application migrating from using Container Registry (available by default on all projects) to Artifact Registry, it looks like the deployment method you used didn't create the registry. At the moment, this application presumes using the US multi-region for this registry (resulting in us-docker.pkg.dev URLs). 

The workaround for now is to run the setup script: 

```

gcloud artifacts repositories create containers \
    --repository-format=docker \
    --location=us
```

The more correct solution is for the deployment to create this artifact registry for you, respecting the region selected, and ensuring all scripts reference the region selection. 

(Developer note: the avocano-based setup creates the artifact registry, but the terraform-based setup doesn't, relying on the pre-created container for deployment. The registry should be created on deployment, noting it won't be used. Alternatively, the registry should be created before this `gcloud builds submit` step of this tutorial)

**Comment by carlosaenz26** [comment]
Hey guys, 
as metioned above  i ran 
gcloud artifacts repositories create containers \
    --repository-format=docker \
    --location=us

after doing so in the 3 step, one must Update this job to use the image I just built, which includes my code changes.  so I ran 
gcloud run jobs update \
    migrate${DEPLOY_SUFFIX} \
    --image \
    gcr.io/${PROJECT_ID}/server \
    --region $REGION

but I got this error:
 X  Updating job... Image 'gcr.io/myprojectid/server' not found.                                                                                                                                      
Job failed to deploy
I understand that the image is now in the containers right? if so how in the job do specify that? 

please help

**Comment by glasnt** [comment]
This should now be resolved.
