### ISSUE TITLE
🐞 [Bug Report] - Cannot develop locally, CORS errors

### ISSUE THREAD

**Issue by glasnt** [GoogleCloudPlatform/avocano#97]
**Describe the bug**

After merging #72, users are successfully able to do local development in Cloud Shell

However, as a Avocano maintainer, I'm no longer able to do development on my local machine. 

**To Reproduce**
1. In one terminal, run `cd server; python manage.py runserver`
2. In another terminal, run `cd client; npm run start`
3. Open `localhost:8081`
4. Note website fails to load.
5. See console error: 

```
localhost/:1 Access to fetch at 'http://localhost:8000/api/active/site_config/' from 
origin 'http://localhost:8081' has been blocked by CORS policy: The value of the 
'Access-Control-Allow-Origin' header in the response must not be the wildcard 
'*' when the request's credentials mode is 'include'.
```

**Expected behavior**
No error, a working website. 
**Screenshots**

**Additional context**

**Comment by glasnt** [comment]
If I adjust the `fetch` requests to optionally use `omit` or `same-origin` instead of `include`, I can locally develop, but I can no longer use Cloud Shell. 

```diff
export const getProduct = async productId => {
   const { API_URL } = getConfig();
   let product;
 
+  var credentials = 'include';
+  if (API_URL.includes('//localhost')) {
+    credentials = 'omit';
+  }
+
   if (productId) {
     try {
       const response = await fetch(`${API_URL}/products/${productId}`, {
         method: 'GET',
-        credentials: 'include',
+        credentials: credentials,
       });
```

Error on Cloud Shell: 

```
Access to fetch at 'https://8000-cs-NUMBER-default.cs-asia-southeast1-bool.cloudshell.dev/api/active/site_config/'
from origin 'https://8081-cs-NUMBER-default.cs-asia-southeast1-bool.cloudshell.dev'
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the 
requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' 
to fetch the resource with CORS disabled.
```

Within Cloud Shell, the API_URL is `localhost:8081` (default), but the Web Preview is making this URL effectively the *.cloudshell.dev value. 

Cloud Shell development is a documented path in upstream tutorial, needs to continue working.

**Comment by glasnt** [comment]
@pattishin would appreciate your insights here.

**Comment by pattishin** [comment]
Sure thing, will take this on today.

**Comment by glasnt** [comment]
Improvements in 113 meant `credentials` is now variable based. 160 should correct the development cycle locally. 

There could be additional improvements, including splitting the settings into Local, Cloud Shell (via checking for the `CLOUD_SHELL` envvar), and Cloud Run (via current metadata server methods, or otherwise).
